import time
print("hi ! welcome to the world of wonders ")
time.sleep(3)
print(" I am here to present you a trick")
time.sleep(3)
print(" the trick is that you first imagines a number and I find it")
time.sleep(3)
print("imagine a number in your mind and do not say it me")
time.sleep(3)
print("add a 10 to the number ")
time.sleep(3)
print("add a 20 to the number")
time.sleep(3)
print("add a 30 to the number")
time.sleep(3)
print("add a 40 to the number")
time.sleep(3)
print("add a 50 to the number")
time.sleep(3)
print("add a 100 to the number")
time.sleep(3)
print("add a 200 to the number")
time.sleep(3)
print("add a 300 to the number")
time.sleep(3)
print(" now substract the number you have imagined first")
time.sleep(3)
sum=(10+20+30+40+50+100+200+300)
time.sleep(3)
print("the number you have now now is",sum,"am I right")
time.sleep(3)
print("thank you for your corporation.visit again!!")
